// <auto-generated />
using System;
using InwentarzWGospodarstwie.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InwentarzWGospodarstwie.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260116234309_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Gospodarstwo", b =>
                {
                    b.Property<int>("IdGodpodarstwa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Godpodarstwa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGodpodarstwa"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdWlasciciela")
                        .HasColumnType("int")
                        .HasColumnName("ID_Wlasciciela");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Powierzchnia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGodpodarstwa");

                    b.HasIndex("IdWlasciciela");

                    b.ToTable("gospodarstwo", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Karmienie", b =>
                {
                    b.Property<int>("IdKarmienia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Karmienia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKarmienia"));

                    b.Property<decimal>("Cena")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("DataZakupu")
                        .HasColumnType("date")
                        .HasColumnName("Data zakupu");

                    b.Property<int>("IdZwierzecia")
                        .HasColumnType("int")
                        .HasColumnName("ID_Zwierzecia");

                    b.Property<string>("Ilość")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rodzaj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdKarmienia");

                    b.HasIndex("IdZwierzecia");

                    b.ToTable("karmienie", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Lekarz", b =>
                {
                    b.Property<int>("IdLekarza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Lekarza");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLekarza"));

                    b.Property<string>("Imię")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("IdLekarza");

                    b.ToTable("lekarz", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("LekarzId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("WlascicielId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LekarzId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("WlascicielId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Wlasciciel", b =>
                {
                    b.Property<int>("IdWlasciciela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Wlasciciela");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWlasciciela"));

                    b.Property<string>("EMail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("E-mail");

                    b.Property<string>("Imię")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("IdWlasciciela");

                    b.ToTable("wlasciciel", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Zabieg", b =>
                {
                    b.Property<int>("IdZabiegu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Zabiegu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZabiegu"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdLekarza")
                        .HasColumnType("int")
                        .HasColumnName("ID_Lekarza");

                    b.Property<int>("IdZwierzecia")
                        .HasColumnType("int")
                        .HasColumnName("ID_Zwierzecia");

                    b.Property<decimal>("Koszt")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdZabiegu");

                    b.HasIndex("IdLekarza");

                    b.HasIndex("IdZwierzecia");

                    b.ToTable("zabieg", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Zwierze", b =>
                {
                    b.Property<int>("IdZwierzecia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Zwierzecia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZwierzecia"));

                    b.Property<decimal?>("CenaSprzedaży")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cena sprzedaży");

                    b.Property<decimal?>("CenaZakupu")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cena zakupu");

                    b.Property<DateOnly?>("DataSprzedażyŚmierci")
                        .HasColumnType("date")
                        .HasColumnName("Data sprzedaży/śmierci");

                    b.Property<DateOnly>("DataZakupuUrodzenia")
                        .HasColumnType("date")
                        .HasColumnName("Data zakupu/urodzenia");

                    b.Property<int>("IdGospodarstwa")
                        .HasColumnType("int")
                        .HasColumnName("ID_Gospodarstwa");

                    b.Property<int>("IdentyfikatorKolczyka")
                        .HasColumnType("int")
                        .HasColumnName("Identyfikator kolczyka");

                    b.Property<string>("Płeć")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rasa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Waga")
                        .HasColumnType("real");

                    b.Property<int?>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("IdZwierzecia");

                    b.HasIndex("IdGospodarstwa");

                    b.ToTable("zwierze", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Gospodarstwo", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.Wlasciciel", "IdWlascicielaNavigation")
                        .WithMany("Gospodarstwos")
                        .HasForeignKey("IdWlasciciela")
                        .IsRequired();

                    b.Navigation("IdWlascicielaNavigation");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Karmienie", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.Zwierze", "IdZwierzeciaNavigation")
                        .WithMany("Karmienies")
                        .HasForeignKey("IdZwierzecia")
                        .IsRequired();

                    b.Navigation("IdZwierzeciaNavigation");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.User", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.Lekarz", "Lekarz")
                        .WithMany()
                        .HasForeignKey("LekarzId");

                    b.HasOne("InwentarzWGospodarstwie.Models.Wlasciciel", "Wlasciciel")
                        .WithMany()
                        .HasForeignKey("WlascicielId");

                    b.Navigation("Lekarz");

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Zabieg", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.Lekarz", "IdLekarzaNavigation")
                        .WithMany("Zabiegs")
                        .HasForeignKey("IdLekarza")
                        .IsRequired();

                    b.HasOne("InwentarzWGospodarstwie.Models.Zwierze", "IdZwierzeciaNavigation")
                        .WithMany("Zabiegs")
                        .HasForeignKey("IdZwierzecia")
                        .IsRequired();

                    b.Navigation("IdLekarzaNavigation");

                    b.Navigation("IdZwierzeciaNavigation");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Zwierze", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.Gospodarstwo", "IdGospodarstwaNavigation")
                        .WithMany("Zwierzes")
                        .HasForeignKey("IdGospodarstwa")
                        .IsRequired();

                    b.Navigation("IdGospodarstwaNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InwentarzWGospodarstwie.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InwentarzWGospodarstwie.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Gospodarstwo", b =>
                {
                    b.Navigation("Zwierzes");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Lekarz", b =>
                {
                    b.Navigation("Zabiegs");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Wlasciciel", b =>
                {
                    b.Navigation("Gospodarstwos");
                });

            modelBuilder.Entity("InwentarzWGospodarstwie.Models.Zwierze", b =>
                {
                    b.Navigation("Karmienies");

                    b.Navigation("Zabiegs");
                });
#pragma warning restore 612, 618
        }
    }
}
